_wandb:
    value:
        cli_version: 0.25.0
        e:
            feyg7t2zeug9zfba9djkz7uiuorvuyj8:
                codePath: src\train.py
                codePathLocal: src\train.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "247462883328"
                        used: "52276924416"
                email: da25m017@smail.iitm.ac.in
                executable: D:\Conda\envs\myenv\python.exe
                host: yaqoob
                memory:
                    total: "16907886592"
                os: Windows-10-10.0.26200-SP0
                program: D:\IIT Madras\2nd Mtech\DL\Assignments\395380985\src\train.py
                python: CPython 3.10.18
                root: D:\IIT Madras\2nd Mtech\DL\Assignments\395380985
                startedAt: "2026-03-06T18:14:36.599653Z"
                writerId: feyg7t2zeug9zfba9djkz7uiuorvuyj8
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 105
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 105
            "3":
                - 2
                - 16
            "4": 3.10.18
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
activation:
    value: relu
batch_size:
    value: 64
dataset:
    value: mnist
epochs:
    value: 15
hidden_size:
    value:
        - 128
learning_rate:
    value: 0.001
loss:
    value: cross_entropy
no_wandb:
    value: false
num_layers:
    value: 3
optimizer:
    value: adam
save_dir:
    value: models
seed:
    value: 42
val_split:
    value: 0.1
wandb_entity:
    value: null
wandb_project:
    value: da6401_assignment_1
weight_decay:
    value: 0
weight_init:
    value: xavier
